import 'package:flutter/material.dart';

void main()=>runApp(const Aghinou());
class Aghinou extends StatelessWidget{const Aghinou({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'آگهینو',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:const Color(0xfff8f7fc),colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff6d45e8)),cardTheme:CardThemeData(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(20)))),home:const Directionality(textDirection:TextDirection.rtl,child:Home()));}

const ads=[
 ['آیفون ۱۳، ۱۲۸ گیگ، بسیار تمیز','۳۸,۵۰۰,۰۰۰ تومان','رشت، گلسار','۸ دقیقه پیش','موبایل'],
 ['مبل راحتی ۷ نفره، سالم و شیک','۲۴,۰۰۰,۰۰۰ تومان','آستارا، مرکز شهر','۲۵ دقیقه پیش','خانه'],
 ['پژو ۲۰۶ تیپ ۵ مدل ۱۳۹۹','۶۹۰,۰۰۰,۰۰۰ تومان','اردبیل','۴۳ دقیقه پیش','خودرو'],
 ['لپ‌تاپ Lenovo IdeaPad، سالم','۳۲,۰۰۰,۰۰۰ تومان','رشت، منظریه','۱ ساعت پیش','دیجیتال'],
 ['آپارتمان ۹۰ متری، دو خواب','قیمت توافقی','آستارا، ساحل','۲ ساعت پیش','املاک'],
];
const pics=['https://images.unsplash.com/photo-1592286927505-2fd7f7f2f4c7?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80'];

class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{int tab=0;String cat='همه';final q=TextEditingController();final cats=['همه','خودرو','املاک','موبایل','دیجیتال','خانه','پوشاک','خدمات'];
@override Widget build(BuildContext c){if(tab==1)return const SearchScreen();if(tab==3)return const MessagesScreen();if(tab==4)return const ProfileScreen();final shown=List.generate(ads.length,(i)=>i).where((i)=>(cat=='همه'||ads[i][4]==cat)&&(q.text.isEmpty||ads[i].join(' ').contains(q.text))).toList();return Scaffold(body:SafeArea(child:RefreshIndicator(onRefresh:()async{},child:ListView(padding:const EdgeInsets.fromLTRB(18,14,18,110),children:[
Row(children:[Container(width:48,height:48,decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xff7b52f0),Color(0xff4d2cb5)]),borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.storefront_rounded,color:Colors.white)),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('سلام 👋',style:TextStyle(color:Colors.grey)),Text('آگهینو',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900))])),IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none_rounded))]),
const SizedBox(height:18),TextField(controller:q,onChanged:(_)=>setState((){}),decoration:InputDecoration(hintText:'دنبال چه چیزی می‌گردی؟',prefixIcon:const Icon(Icons.search_rounded),suffixIcon:const Icon(Icons.tune_rounded),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(19),borderSide:BorderSide.none))),
const SizedBox(height:14),Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xffefeaff),borderRadius:BorderRadius.circular(17)),child:const Row(children:[Icon(Icons.location_on_rounded,color:Color(0xff6d45e8)),SizedBox(width:8),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('موقعیت شما',style:TextStyle(fontSize:11,color:Colors.grey)),Text('آستارا',style:TextStyle(fontWeight:FontWeight.bold))])),Text('تغییر شهر',style:TextStyle(color:Color(0xff6d45e8),fontWeight:FontWeight.bold))])),
const SizedBox(height:22),const Text('دسته‌بندی‌ها',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:10),
SizedBox(height:91,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:cats.length,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i){final active=cat==cats[i];return GestureDetector(onTap:()=>setState(()=>cat=cats[i]),child:Column(children:[Container(width:59,height:59,decoration:BoxDecoration(color:active?const Color(0xff6d45e8):Colors.white,borderRadius:BorderRadius.circular(18)),child:Icon([Icons.apps,Icons.directions_car_filled_rounded,Icons.home_work_rounded,Icons.smartphone_rounded,Icons.devices_rounded,Icons.weekend_rounded,Icons.checkroom_rounded,Icons.handyman_rounded][i],color:active?Colors.white:const Color(0xff6d45e8))),const SizedBox(height:5),Text(cats[i],style:TextStyle(fontSize:11,fontWeight:active?FontWeight.bold:FontWeight.normal))]));})),
const SizedBox(height:18),Row(children:[const Text('آگهی‌های ویژه',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const Spacer(),Text('مشاهده همه',style:TextStyle(color:Color(0xff6d45e8),fontWeight:FontWeight.bold))]),const SizedBox(height:10),
SizedBox(height:205,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:2,separatorBuilder:(_,__)=>const SizedBox(width:12),itemBuilder:(_,i)=>ClipRRect(borderRadius:BorderRadius.circular(22),child:SizedBox(width:300,child:Stack(fit:StackFit.expand,children:[Image.network(pics[i],fit:BoxFit.cover),DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.transparent,Colors.black.withValues(alpha:.8)]))),Positioned(right:14,bottom:14,left:14,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(ads[i][0],maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:16)),Text(ads[i][1],style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold)),Text(ads[i][2],style:const TextStyle(color:Colors.white70,fontSize:12))])),const Positioned(top:12,right:12,child:Chip(label:Text('ویژه',style:TextStyle(color:Colors.white)),backgroundColor:Color(0xff6d45e8))]))))),
const SizedBox(height:26),Row(children:[const Text('آگهی‌های جدید',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const Spacer(),Text('مرتب‌سازی',style:TextStyle(color:Color(0xff6d45e8),fontWeight:FontWeight.bold))]),const SizedBox(height:10),for(final i in shown)AdTile(i:i)
]))),floatingActionButton:FloatingActionButton.extended(backgroundColor:const Color(0xff6d45e8),foregroundColor:Colors.white,onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const CreateAd())),icon:const Icon(Icons.add),label:const Text('ثبت آگهی',style:TextStyle(fontWeight:FontWeight.bold))),floatingActionButtonLocation:FloatingActionButtonLocation.centerFloat,bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v){if(v==2){Navigator.push(c,MaterialPageRoute(builder:(_)=>const CreateAd()));}else setState(()=>tab=v);},destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'خانه'),NavigationDestination(icon:Icon(Icons.search),label:'جست‌وجو'),NavigationDestination(icon:Icon(Icons.add_circle_outline),label:'ثبت آگهی'),NavigationDestination(icon:Icon(Icons.chat_bubble_outline),label:'پیام‌ها'),NavigationDestination(icon:Icon(Icons.person_outline),label:'پروفایل')]));}
}
class AdTile extends StatefulWidget{final int i;const AdTile({super.key,required this.i});@override State<AdTile> createState()=>_AdTileState();}
class _AdTileState extends State<AdTile>{bool saved=false;@override Widget build(BuildContext c)=>GestureDetector(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>AdDetail(i:widget.i))),child:Container(margin:const EdgeInsets.only(bottom:11),padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xffece9f2))),child:Row(children:[ClipRRect(borderRadius:BorderRadius.circular(15),child:Image.network(pics[widget.i],width:108,height:108,fit:BoxFit.cover)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(ads[widget.i][0],maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:15)),const SizedBox(height:8),Text(ads[widget.i][1],style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:7),Text('\${ads[widget.i][2]} • \${ads[widget.i][3]}',style:const TextStyle(fontSize:11,color:Colors.grey))])),IconButton(onPressed:()=>setState(()=>saved=!saved),icon:Icon(saved?Icons.favorite:Icons.favorite_border,color:saved?Colors.pink:Colors.grey))])));}
class AdDetail extends StatelessWidget{final int i;const AdDetail({super.key,required this.i});@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:CustomScrollView(slivers:[SliverAppBar(expandedHeight:320,pinned:true,actions:[IconButton(onPressed:(){},icon:const Icon(Icons.share)),IconButton(onPressed:(){},icon:const Icon(Icons.favorite_border))],flexibleSpace:FlexibleSpaceBar(background:Image.network(pics[i],fit:BoxFit.cover))),SliverPadding(padding:const EdgeInsets.all(20),sliver:SliverToBoxAdapter(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(ads[i][0],style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:10),Text(ads[i][1],style:const TextStyle(fontSize:21,color:Color(0xff6d45e8),fontWeight:FontWeight.w900)),const SizedBox(height:20),const Text('توضیحات آگهی',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('این آگهی نمونه نسخه جدید آگهینو است. در نسخه نهایی، مشخصات کامل، اطلاعات فروشنده، بازدید، ذخیره، گزارش، پیام و آگهی‌های مشابه از Backend واقعی نمایش داده می‌شود.',style:TextStyle(height:1.8,color:Colors.grey)),const SizedBox(height:20),const ListTile(leading:CircleAvatar(child:Icon(Icons.person)),title:Text('فروشنده آگهینو'),subtitle:Text('عضو فعال • مشاهده پروفایل'),trailing:Icon(Icons.chevron_left))])))]),bottomNavigationBar:SafeArea(child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:FilledButton.icon(onPressed:(){},icon:const Icon(Icons.chat),label:const Text('پیام'))),const SizedBox(width:10),Expanded(child:OutlinedButton.icon(onPressed:(){},icon:const Icon(Icons.phone),label:const Text('تماس')))]))));}
class CreateAd extends StatelessWidget{const CreateAd({super.key});@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('ثبت آگهی جدید')),body:ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xff6d45e8),Color(0xff8e6af2)]),borderRadius:BorderRadius.circular(22)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('آگهی خودت را بساز ✨',style:TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),SizedBox(height:6),Text('اشتراک فعال: تا ۹ آگهی در یک ماه',style:TextStyle(color:Colors.white70))])),const SizedBox(height:15),for(final x in [['دسته‌بندی','دسته و زیر‌دسته آگهی'],['اطلاعات آگهی','عنوان، توضیحات، قیمت و وضعیت'],['موقعیت','شهر، محله و موقعیت تقریبی'],['تصاویر','حداکثر ۱۰ عکس و عکس اصلی'],['پیش‌نمایش','بررسی نهایی و انتشار']])Card(child:ListTile(leading:const CircleAvatar(backgroundColor:Color(0xffefeaff),child:Icon(Icons.check,color:Color(0xff6d45e8))),title:Text(x[0],style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text(x[1]),trailing:const Icon(Icons.chevron_left))),const SizedBox(height:8),FilledButton(onPressed:(){},child:const Padding(padding:EdgeInsets.all(13),child:Text('شروع ثبت آگهی')))]));}
class SearchScreen extends StatelessWidget{const SearchScreen({super.key});@override Widget build(BuildContext c)=>const Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:Center(child:Text('جست‌وجوی پیشرفته آگهینو'))));}
class MessagesScreen extends StatelessWidget{const MessagesScreen({super.key});@override Widget build(BuildContext c)=>const Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:Center(child:Text('پیام‌های آگهینو'))));}
class ProfileScreen extends StatelessWidget{const ProfileScreen({super.key});@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('پروفایل')),body:ListView(padding:const EdgeInsets.all(18),children:[const CircleAvatar(radius:45,child:Icon(Icons.person,size:48)),const SizedBox(height:10),const Center(child:Text('کاربر آگهینو',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900))),const SizedBox(height:20),for(final x in ['آگهی‌های من','ذخیره‌شده‌ها','اشتراک من','پرداخت‌ها','تنظیمات'])Card(child:ListTile(title:Text(x),trailing:const Icon(Icons.chevron_left)))]));}
