from pathlib import Path
import re

p = Path('lib/main.dart')
s = p.read_text(encoding='utf-8')

required_imports = [
    "import 'package:shared_preferences/shared_preferences.dart';",
    "import 'package:flutter_map/flutter_map.dart';",
    "import 'package:latlong2/latlong.dart';",
    "import 'package:url_launcher/url_launcher.dart';",
]
anchor = "import 'package:geolocator/geolocator.dart';"
for imp in required_imports:
    if imp not in s:
        if anchor in s:
            s = s.replace(anchor, anchor + '\n' + imp, 1)
        else:
            s = imp + '\n' + s
        anchor = imp

# The integrated category page needs the icon map exactly once.
icon_map = """const Map<String, IconData> aghinouCategoryIcons = <String, IconData>{
  'خودرو': Icons.directions_car_rounded,
  'املاک': Icons.home_work_rounded,
  'موبایل': Icons.phone_iphone_rounded,
  'لوازم خانه': Icons.chair_rounded,
  'کالای دیجیتال': Icons.devices_rounded,
  'پوشاک': Icons.checkroom_rounded,
  'خدمات': Icons.handyman_rounded,
};
"""
# Remove every generated category icon map, then insert one before categoryNames.
s = re.sub(r"\n?const Map<String, IconData> aghinouCategoryIcons = <String, IconData>\{.*?\n\};\n", "\n", s, flags=re.S)
marker = "const categoryNames = ['همه', 'خودرو', 'املاک', 'موبایل', 'لوازم خانه', 'کالای دیجیتال', 'پوشاک', 'خدمات'];"
if marker in s and 'aghinouCategoryIcons' not in s:
    s = s.replace(marker, icon_map + '\n' + marker, 1)

# Normalize _categoryColor: remove all generated copies and insert one canonical helper.
color_helper = """Color _categoryColor(String name) {
  const colors = <String, Color>{
    'خودرو': Color(0xFFEF5350),
    'املاک': Color(0xFF42A5F5),
    'موبایل': Color(0xFFAB47BC),
    'لوازم خانه': Color(0xFF26A69A),
    'کالای دیجیتال': Color(0xFF5C6BC0),
    'پوشاک': Color(0xFFEC407A),
    'خدمات': Color(0xFFFFA726),
  };
  return colors[name] ?? const Color(0xFF6C4CF1);
}
"""
# This exact helper shape is generated by the integration script. Remove all copies.
s = re.sub(r"\n?Color _categoryColor\(String name\) \{.*?return colors\[name\] \?\? const Color\(0xFF6C4CF1\);\n\}\n", "\n", s, flags=re.S)
if marker in s:
    s = s.replace(marker, color_helper + '\n' + marker, 1)

# Remove duplicate CityPicker declarations while retaining the first implementation.
starts = [m.start() for m in re.finditer(r'class CityPicker extends StatefulWidget \{', s)]
if len(starts) > 1:
    second = starts[1]
    next_class = s.find('\nclass ', second + 1)
    if next_class == -1:
        next_class = len(s)
    s = s[:second] + s[next_class:]

# Keep uploads reasonably sized for mobile/storage reliability.
s = s.replace('picker.pickMultiImage(imageQuality: 85)', 'picker.pickMultiImage(imageQuality: 70, maxWidth: 1600, maxHeight: 1600)')
s = s.replace('_picker.pickMultiImage(imageQuality: 85)', '_picker.pickMultiImage(imageQuality: 70, maxWidth: 1600, maxHeight: 1600)')

p.write_text(s, encoding='utf-8')
print('Final Aghinou polish applied safely.')
